### ISSUE TITLE
New FAQ: "How to I write BNF"

### ISSUE THREAD

**Issue by jeffreykegler** [ronsavage/marpa.faq#5]
Great work!

Title: "How to I write BNF to specify exceptions ..". Typo: s/to/do/.

Graf 1: Change "Currently there is no way to do that," to "Currently there is no way to specify that directly in Marpa::R2,"

Graf 2:  "IOW ...".  Delete it.  It's *not* a proof of Graf 1, but a separate issue, and something of a digression from the question.

**Comment by ronsavage** [comment]
Updated and uploaded. Thanx.
